### ISSUE TITLE
Documentation du modèle conceptuel

### ISSUE THREAD

**Issue by atterebf** [spanzerotto/italian_poets_XX#6]
Outre le catalogue des informations, qui documente une première étape de la recherche, et est plus large que l'information effectivement collectée dans la base de données,
il faudrait ajouter un commentaire détaillé du modèle conceptuel (fichier drawio) en suivant [cet exemple](https://github.com/Sciences-historiques-numeriques/astronomers/wiki/Modèle-conceptuel-(MCD):-commentaire)

**Comment by spanzerotto** [comment]
Bonjour @atterebf ,
j'ai ajouté la page de commentaire du modèle conceptuel. Comme vous pourriez voir, la seul chose dont je ne suis pas sure c'est la typologie des classes "Appellation", "Geographical place type" and "Implication", que je ne considère pas "persistent item" mais même pas "temporal entity". Comment les classifier alors? Merci en avance!
