### ISSUE TITLE
Commentaires au MCD

### ISSUE THREAD

**Issue by atterebf** [spanzerotto/italian_poets_XX#7]
Quelques commentaires:

*   pour la propriété qui associe Membership à la personne, mieux mettre le sens vers la personne (d'autant plus que c'est n à 1), comme pour toutes les autres temporalités
    *   même logique pour 'Implication', 'Reference'
*   Classe Pursuit: s'agit-il plutôt de membership ?
*   Party et Organisation sont en fait la même classe: Organisation ou groupe, avec un type
*   je ne suis pas sûr de comprendre la classe 'Reference', ce sera plus clair un fois rédigé le commentaire du MCD, cf. l'autre issue

**Comment by spanzerotto** [comment]
À nouveau bonjour @atterebf et merci pour les commentaires: j'ai pris note et changé selon votre avis. Comme vous verriez, la classe "reference" exprime l'appartenance (formelle ou pas) d'un periodique à un parti politique. Le nom "reference" en fait n'est pas le meilleur, mais honnêtement je n'avais d'autre inspo... je reste ouverte à toute suggestion :)
 Un point que pourtant ne me convaic pas c'est d'unir les classes Party et Institution. En fait ils ont propriétés et relations differents, et sa me semblait plus clair les laisser separée... Faites moi savoir qu'est ce que vous en pensez, et si jamais je vais faire cette dernière modification dans un deuxième moment.
Je vous souhaite une bonne semaine!
